- name: "get list of MTA packages (keep only postfix)"
  shell: |
      dpkg -l | awk '/^ii/ { print $2 }' \
      | grep -E 'sendmail|exim|ssmtp|nullmailer|msmtp|bsd-mailx' || true 
  register: unwanted_mtas
  ignore_errors: true
  changed_when: false

- name: "show unwanted MTA packages found"
  debug:
    msg: >-
      {{
        (unwanted_mtas.stdout_lines | length > 0)
        | ternary("Unwanted MTA packages: " ~ (unwanted_mtas.stdout_lines | join(', ')),
                  "No unwanted MTA packages found."
      )
      }}

- name: "stop unwanted MTA services"
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ unwanted_mtas.stdout_lines }}"
  when: unwanted_mtas.stdout_lines | length > 0
  ignore_errors: true     

- name: "remove unwanted MTA packages"
  apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ unwanted_mtas.stdout_lines }}"
  when: unwanted_mtas.stdout_lines | length > 0
  tags: [remove_mtas]

- name: "preseed Postfix configuration"
  debconf:
    name: postfix
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop:
    - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'select' }
    - { question: 'postfix/mailname', value: "{{ postfix_myhostname }}", vtype: 'string' }

- name: Configure startup after docker.service
  # Ensures that the networks are configured at startup
  block:
    - name: Create /etc/systemd/system/postfix.service.d
      ansible.builtin.file:
        path: /etc/systemd/system/postfix.service.d
        state: directory

    - name: Place systemd config postfix.service.d/after-docker.conf
      ansible.builtin.copy:
        dest: /etc/systemd/system/postfix.service.d/after-docker.conf
        content: |
          [Unit]
          After=docker.service
          Wants=docker.service

- name: "install Postfix"
  apt:
    name: postfix
    state: present
    update_cache: yes

- name: "install mailutils"
  apt:
    name: mailutils
    state: present
    update_cache: yes

- name: configure postfix
  block:
    - name: "replace relayhost"
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^relayhost[\s]*='
        line: 'relayhost = {{ postfix_relayhost }}'
      notify:
        - validate configuration and reload postfix
        - send test email

    - name: configure mydestination
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^mydestination[\s]*='
        line: mydestination =
      notify:
        - validate configuration and reload postfix

    - name: "replace myhostname"
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^myhostname[\s]*='
        line: 'myhostname = {{ postfix_myhostname  }}'
      notify:
       - validate configuration and reload postfix
       - send test email

    - name: "replace myorigin"
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^myorigin[\s]*='
        line: 'myorigin = $mydomain'
      notify:
        - validate configuration and reload postfix
        - send test email

    - name: "replace mydomain"
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^mydomain[\s]*='
        line: 'mydomain = {{ postfix_mydomain }}'
      notify:
        - validate configuration and reload postfix
        - send test email

    - name: "replace smtp_tls_security_level"
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^smtp_tls_security_level[\s]*='
        line: 'smtp_tls_security_level = {{ postfix_smtp_tls_security_level }}'
      notify:
        - validate configuration and reload postfix
        - send test email

    - name: Configure smtpd_tls_security_level
      # Assumption: postfix is operating only on local network interface, no encryption for local traffic is needed
      lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^smtpd_tls_security_level[\s]*='
        line: smtpd_tls_security_level = none
      notify:
        - validate configuration and reload postfix

    - name: "ensure canonical file exists with desired mappings"
      ansible.builtin.template:
        dest: /etc/postfix/canonical
        src: canonical.j2
        owner: root
        group: root
        mode: '0644'
      notify:
        - rebuild canonical map
        - validate configuration and reload postfix
        - send test email

    - name: "ensure generical file exists with desired mappings"
      ansible.builtin.template:
        dest: /etc/postfix/generic
        src: generic.j2
        owner: root
        group: root
        mode: '0644'
      notify:
        - rebuild generic map
        - validate configuration and reload postfix
        - send test email

    - name: "create sasl_passwd"
      copy:
        dest: /etc/postfix/sasl_passwd
        content: "{{ postfix_sasl_passwd }}"
        owner: root
        group: root
        mode: "0600"
      when: postfix_use_login
      notify:
        - validate configuration and reload postfix


    - name: "create hash DB for sasl_passwd"
      command: postmap /etc/postfix/sasl_passwd
      when: postfix_use_login
      notify:
        - validate configuration and reload postfix

    - name: "configure main.cf with certs"
      blockinfile:
        path: /etc/postfix/main.cf
        block: |
          smtp_tls_cert_file = {{ postfix_smtp_tls_cert_file }}
          smtp_tls_key_file = {{ postfix_smtp_tls_key_file }}
          smtp_tls_security_level = {{ postfix_smtp_tls_security_level }}
          smtp_tls_wrappermode = yes
          smtp_generic_maps = hash:/etc/postfix/generic
          sender_canonical_maps = hash:/etc/postfix/canonical
          smtputf8_enable = no
      when: postfix_use_certs
      notify:
        - validate configuration and reload postfix
        - send test email

    - name: "configure main.cf for login"
      blockinfile:
        path: /etc/postfix/main.cf
        block: |
          smtp_sasl_auth_enable = yes
          smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
          smtp_sasl_security_options = noanonymous
          smtp_sasl_mechanism_filter = plain
          smtp_use_tls = yes
          smtp_tls_cert_check = off
          smtp_tls_wrappermode = no
          smtp_generic_maps = hash:/etc/postfix/generic
          sender_canonical_maps = hash:/etc/postfix/canonical
      when: postfix_use_login
      notify:
        - validate configuration and reload postfix
        - send test email

    #Docker settings
    - name: "create default line in /etc/aliases"
      lineinfile:
        state: present
        path: /etc/aliases
        create: true
        owner: root
        group: root
        mode: '0644'
        regexp: '^default:'
        line: "default: root"
      notify:
        - rebuild aliases
        - validate configuration and reload postfix
        - send test email

    - name: "set up /etc/aliases for postfix"
      loop:
        - postmaster
        - postgres
        - perun
        - perunrpc
        - peruneng
        - perunldc
      lineinfile:
        path: /etc/aliases
        regexp: "^{{ item }}:"
        line: "{{ item }}: root"
        state: present
      notify:
        - rebuild aliases
        - validate configuration and reload postfix
        - send test email

    - name: "get {{ postfix_for_docker_bridge_network_name }} info"
      docker_network_info:
        name: "{{ postfix_for_docker_bridge_network_name }}"
      register: perun_net_info

    - name: "add {{ postfix_for_docker_bridge_network_name }} bridge network gateway to /etc/hosts to avoid warnings in log"
      lineinfile:
        path: /etc/hosts
        line: "{{ item }} {{ postfix_for_docker_bridge_network_name }}"
      with_list: "{{ perun_net_info.network.IPAM.Config | community.general.json_query('[].Gateway') }}"

    - name: "extract subnets"
      set_fact:
        perun_net_subnets: "{{ perun_net_info.network.IPAM.Config | community.general.json_query('[].Subnet') }}"

    - name: "ensure perun_net subnets are allowed in mynetworks"
      lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^mynetworks ='
        line: "mynetworks = 127.0.0.0/8, [::1/128], [{{ perun_net_subnets | join('], [') }}]"
      notify:
       - validate configuration and reload postfix
       - send test email

    - name: configure inet_interfaces
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^inet_interfaces'
        line: "inet_interfaces = 127.0.0.1, [::1], [{{ perun_net_info.network.IPAM.Config | community.general.json_query('[].Gateway') | join('], [') }}]"
      notify:
        - validate configuration and reload postfix
        - restart postfix
        - send test email

    - name: "ensure /usr/sbin/sendmail.postfix symlink exists"
      file:
        src: /usr/lib/sendmail
        dest: /usr/sbin/sendmail.postfix
        state: link
        force: yes
